class MessageType:
    enum = { 	"LOGIN": "00",
				"LOGOUT" : "01",
				"REGISTER": "02",
				"ACK": "03",
				"CREATE_ROUTE": "04",
				"PRFILEGET_NC": "05",
				"PROFILESET_NC": "06",
				"ROUTE_LIST": "07",
				"GET_ROUTE_DETAILS": "08",
				"GET_TYPE_USER": "09",
				"IS_ROUTE_USER": "10",
				"REGISTER_DRIVER": "11",
                "LOGIN_DRIVER":"12",
                "ROUTE_LIST_DRIVER": "13",
				"PRFILE_VEHICLE": "14",
				"SEND_MESSAGE": "15",
				"MESSAGE_LIST": "16",
				"GET_MESSAGE_DETAILS": "17",
				"GET_DRIVER_NAME": "18",
				"PRFILEGET_NCun": "19",
				"ROUTE_OK": "20",
				"VEHICLESET": "21",
				"GET_VEHICLE_OK": "22",
				"SEND_PUNTUATION": "23",
				"DELETE_MESSAGE": "24",
				"DELETE_VEHICLE": "25",
				"DELETE_ROUTE": "26",
				"GET_ROUTE_ID": "27",
				"IS_ME_MESSAGE": "28",
				"IS_ME_PARTICIPED": "29",
				"IS_PUNTUATION": "30",
				"DRIVER_ACOUNT_ON": "31",
				"DRIVER_ACOUNT_OFF": "32",
				"IS_CONNECTED_DRIVER": "33",
				"GET_IDUSER_ROUTE": "34",
				"GET_BENEFICIE": "35",}
